[package]
name = "mmck_queue_test"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
sysinfo = "0.30"
log = "0.4"
env_logger = "0.10"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"