[package]
name = "ruserial"
version = "0.1.0"
edition = "2024"

[lib]
name = "ruserial"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
pyo3 = { version = "0.20", features = ["extension-module"] }

[build-dependencies]
cc = "1.0"